# Site settings
title: Diário da felicidade
description: O diário de um período sabático indeterminado
keywords: Felicidade, Blogging, Caminhada, Cozinha, Vida, Yoga
author: Fernanda da Mata
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
